logging:
  version: 1
  disable_existing_loggers: False

  formatters:
    simple:
      format: "%(asctime)s %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
    error:
      format: "%(asctime)s %(name)s %(levelname)s %(filename)s::%(funcName)s[%(lineno)d]:%(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout

    info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: simple
      filename: wx_info.log
      maxBytes: 10485760  # 10MB
      backupCount: 20
      encoding: utf8

    error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: error
      filename: wx_error.log
      maxBytes: 10485760  # 10MB
      backupCount: 20
      encoding: utf8

  root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]

groups:
  enable: [] # 允许响应的群 roomId，大概长这样：2xxxxxxxxx3@chatroom

news:
  receivers: [] # 定时新闻接收人（roomid 或者 wxid）

report_reminder:
  receivers: []  # 定时日报周报月报提醒（roomid 或者 wxid）

chatgpt:  # -----chatgpt配置这行不填-----
  key: 
  api: https://api.openai.com/v1  # 如果你不知道这是干嘛的，就不要改
  proxy:  # 如果你在国内，你可能需要魔法，大概长这样：http://域名或者IP地址:端口号
  prompt: 你是个乐于助人的AI, 叫做K，乐于帮助人们解决问题。 

# chatglm:  # -----chatglm配置这行不填-----
#   key: sk-012345678901234567890123456789012345678901234567 # 这个应该不用动
#   api: http://localhost:8000/v1  # 根据自己的chatglm地址修改
#   proxy:  # 如果你在国内，你可能需要魔法，大概长这样：http://域名或者IP地址:端口号
#   prompt: 你是智能聊天机器人，你叫小薇  # 根据需要对角色进行设定 
#   file_path: F:/Pictures/temp  #设定生成图片和代码使用的文件夹路径

# tigerbot:  # -----tigerbot配置这行不填-----
#   key:  # key
#   model:  # tigerbot-7b-sft

xinghuo_web:  # -----讯飞星火web模式api配置这行不填 抓取方式详见文档：https://www.bilibili.com/read/cv27066577-----
  cookie: 
  fd: 
  GtToken: 
  prompt: 你是智能聊天机器人，你叫wcferry。请用这个角色回答我的问题  # 根据需要对角色进行设定
